### ISSUE TITLE
ToDo List - (From VuePress to VitePress)

### ISSUE THREAD

**Issue by dacodekid** [dacodekid/dacodekid.com#1]
The current website is running on `VuePress@next` (v2) and since the `Vue` team decided to concentrate on `VitePress` and considering it as `VuePress's` successor (VuePress 3), it's time to move the current site to `VitePress` (currently in RC stage).

There are significant changes between these two's architecture and hence there'll few hurdles on the way.  Here are the lists that needed to be done & considered.

## Current Issues
- [ ] **Theme** - The default theme that comes with `VitePress` is good enough, but still need few patches to match with current theme.
- [ ] **Sidebar** - The `json` files requires several changes to match `VitePress`'s template.
- [ ] **Plugins** - Many of `markdown-it` plugins might work out of the box.  But still may not be able to use all of them.  Here are the current plugins used in `VuePress`.

> - [ ] markdown-it-mathjax3 (it has inbuilt support from `VitePress`, just requires to install the plugin)
> - [ ] markdown-it-plantuml
> - [ ] markdown-it-sub
> - [ ] markdown-it-sup
> - [ ] chartJS
> - [ ] mermaidJS

- [ ] **PlopJS** - `plop.js` and it's template files requires some heavy changes to accommodate new file structures & locations.
- [ ] **Content Files** - Markdown files requires to be modified - for things like `relative paths`, `code-groups` syntax, etc.

## Features for the Future
- [ ] **Blog Template** -  Nice to have and need to  design one in near future.
