### ISSUE TITLE
TODO: Quiz Component

### ISSUE THREAD

**Issue by dacodekid** [dacodekid/dacodekid.com#1]
- Each Question must have 
   - [x] 1 Question
   - [x] 4 Options with each has a key of A, B, C & D
   - [x] 1 Answer that has one of these Keys
   - [x] 1 Explanation
   
- Component should have the following
   - [x] Previous Button to move backward
   - [x] Next Button to move forward 
   - [x] Finish Button to end the Quiz
   - [x] Show / Hide Button for Correct Answer & Explanation
   - [x] Zen Mode Button that hides all other elements (ex: Sidebar & NavBar)
   - [x] Feedback text (Correct / Incorrect) when an option is selected
   - [x] Current Question Indicator (ex: 1/200)
   - [x] Current Question Indicator should able to go to any question within the range
   - [x] Timer that starts soon after the an option selected for a question / or Question's index changed
   - Result Page that contains
      - [x] Shows Pass / Fail
      - [x] Score %
      - [x] Passing Score (ex: 70%)
      - [x] Number of Correct Answers
      - [x] Number of Incorrect Answers
      - [x] Number of Unanswered Questions
      - [x] Retake Button that resets the Quiz and go back to question 1
      - [x] Review Button that'll in 'read-only' mode and a different color border as a review-mode indicator.
